### ISSUE TITLE
Notice Module could use some ARIA love

### ISSUE THREAD

**Issue by kabel** [unl/wdntemplates#881]
The notice module has not been fully analyzed for a11y using a manual tool. It could likely use some additional aria attributes, at least for the ones that get moved to the header or to the top of maincontent.

**Comment by mfairchild365** [comment]
I've done some experimenting with this using a few browsers (chrome, firefox and safari) and voiceover and this is what I have found:

1. Browser/AT support for the alert role is sketchy.
See this somewhat dated post: http://www.paciellogroup.com/blog/2012/06/html5-accessibility-chops-aria-rolealert-browser-support/

In short, the `alert` and `alertdialog` roles will only announce the content if the content is dynamically added to the page after first render, and even then only under certain conditions.

The `alert` role does nothing to alert users if it exists on the page when the page is first rendered, which sort of nullifies its usefulness in many cases.  If the user reads the entire page, they will still see the notice, but if they navigate to a specific landmark or heading, they might miss the notice all together.

2. There isn't a very good way to add the roles dynamically with javascript.
I was hoping to implement this so that people using notifications wouldn't have to worry about adding the correct attributes to make them accessible.  In other words, the notification js would auto add all the correct attributes.

This would be easy if all of our notifications were simple `alerts`.  However, they do support more functionality that requires interaction (like closing them, or interacting with the contents of the alert), in which case the `alertdialog` role is more appropriate.  However, the `alertdialog` role needs `aria-label` and `aira-describedby` attributes to be most effective.  See https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alertdialog_role

Dynamically creating the appropriate attributes for notices can be done, but it is complicated by generating unique IDs for the description and labels for each notice on the page.

## So, my suggestion, on which I would like some feedback:

Even though support for alerts is sketchy, I think we should still implement them according to standards.  I can only hope that over time, browsers and AT will better support them. 

1. Update our example page for the notices so that they include appropriate use of the attributes.
2. In the notification js module, add a simple `role=alert` if a role has not been defined by the author.  This will add better support than nothing.
3. Wrap the alert title in the appropriate heading attribute.  It seems logical that an alert deserves its own heading (as long as it is used appropriately), and it will help to ensure that the alert is visible when navigating the page with something like the web rotor.

Thoughts @kabel or anyone else?

**Comment by kabel** [comment]
I'm good with 1 and 2. However, I'm against 3, changing the example markup back to using heading tags. Sure headings are a nice part of the document, but it is difficult to generate a widget that works with the established outline of any page it's dropped into.

Due to the copy/paste nature of the examples and how we know people often put little thought into customizing the example for their purposes, I'm against providing an example that will likely break the outline of the page it's dropped in.
